### ISSUE TITLE
Partial Feed Parsing

### ISSUE THREAD

**Issue by normand1** [nmdias/FeedKit#121]
I'd love a way to parse just part of a feed. Some RSS feeds can be extremely long so it would be nice to just parse certain portions of an RSS feed or a certain number of items as specified.

**Comment by mlm249** [comment]
This would be useful to me too

**Comment by GarthSnyder** [comment]
@normand1 or @mlm249, can you explain the use case for this in a bit more detail?

**Comment by mlm249** [comment]
I'd just like to load only 10 items from a feed, for instance, rather than the thousands that some feeds have.

That being said I'm pretty sure this is the wrong tool for that. After looking into it, seems like this is a feature better suited for services that literally store feeds in a database and produce a single predictable outcome type of data.

**Comment by joshdholtz** [comment]
I was thinking about something like this too! I'm wanting to parse feeds in a a memory sensitive operation. I'm thinking of making a proof of concept and making PR (but no need to take it 😇)

**Comment by GarthSnyder** [comment]
Yes, that would be helpful. I'm still not getting a clear idea of exactly what API is being requested here.
