### ISSUE TITLE
Can not locate image in RSSFeed

### ISSUE THREAD

**Issue by ahmedrezik** [nmdias/FeedKit#130]
An rssfeeditem does not contain an attribute that holds the item's image or it's URL

**Comment by GarthSnyder** [comment]
FeedKit is a relatively thin layer over the RSS format spec (e.g., [here](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt) for feed items). It doesn't add anything that's not in the spec; RSS items do not have images. If the feed itself has an image, you can reasonably impute that image to the items it contains, but since this isn't officially part of RSS, FeedKit doesn't do it for you.

In theory, an item's URL is in the `link` field. But keep in mind that RSS is a folk format, so there are many noncompliant feeds out there. If the link field doesn't contain the type of content that you think it should, you should also check for an `enclosure` of the appropriate type.
