### ISSUE TITLE
Completion block gets executed twice on failure

### ISSUE THREAD

**Issue by mehlkelm** [nmdias/FeedKit#6]
If I parse data which happens to not be a valid feed, the completion block gets executed twice.
In Parser.swift, once in line 119 and once in line 242, which is, I believe an XMLParser delegate method.  I don't know the FeedKit architecture enough to judge which one is superfluous, though.

One way to reproduce the error: Add this in the sample projects applicationDidFinishLaunching:
`let url = URL(string: "https://tageswoche.ch")`
`URLSession.shared.dataTask(with: url! as URL) { (data, response, error) in`
`  FeedParser(data: data!).parse({ (result) in`
`    print("ERROR")`
`  })`
`}.resume()`

You will see that "ERROR" gets printed twice!

**Comment by mehlkelm** [comment]
Hm… now the same happens with the parserDidEndDocument delegate method. Am I misunderstanding this?
Is the call to the completion handler from any delegate method needed at all?

**Comment by nmdias** [comment]
I think I see what's happening. Yes, it is needed in order to provide error information to the user. 

However, from what you're telling me and what i've gathered just by looking at the code I'll need to cancel any subsequent errors to the first error found. I'll take a closer look in the next coming days and cook up a fix. Are you using any public feeds that you could provide to better replicate the error?

Thanks!

**Comment by mehlkelm** [comment]
I have a workflow where the user can input any URL to subscribe to a feed. First I check if the data at the URL happens to be a valid feed (with FeedKit) which it is most often not. That's where I am running into these errors. Examples I used: tageswoche.ch, zoziapps.ch

**Comment by nmdias** [comment]
Ok, so it should be fixed now. 

Great catch by the way, the call to the completion handler from the delegate methods were indeed causing the issues.

Also, there was a check in the `XMLParser`'s `parse()` method to see if it returned false for a failed parsing attempt. This was initially added because if a URL was malformed, it would fail without calling the `XMLParser`'s error delegate method.

I'm fine with not handling malformed URL's at this moment, as there is a bug in Apple's side, described in issue #4 where subclasses of `XMLParser` crash in the `contentsOf:` initializer.
This initializer, when not within a subclass, returns what seems an appropriate error: `Could not open data stream`. However, when subclassing, it just crashes. 


Could you check if it's running fine now?

Thanks :)

**Comment by mehlkelm** [comment]
Looks fine. Thanks for the quick fix!
